name=VCANESP32
version=0.1.1
author=Duncan Greenwood (duncan_greenwood@hotmail.com)
maintainer=Duncan Greenwood (duncan_greenwood@hotmail.com)
sentence=Library for VLCB use on ESP32
paragraph=Implements functionality required to create a VLCB module based on built-in TWAI controller
category=Communication
url=https://github.com/obdevel/VCANESP32
architectures=esp32
includes=VLCB-Arduino
depends=Streaming
